# Meta Data for SEO

## Homepage
title = "Alex Stephen"
titleSeparator = "|"
titleAddition = ""
description = "Alex Stephen's website"

## Open Graph
images = ["me.png"]
ogLocale = "en_US"
titleHome = "Alex Stephen"

## Twitter Cards
twitterSite = "@rambleraptor"
twitterCreator = "@rambleraptor"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Alex Stephen"
schemaAuthor = "Alex Stephen"
schemaAuthorTwitter = "https://twitter.com/rambleraptor"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/rambleraptor/"
schemaAuthorGitHub = "https://github.com/rambleraptor"
schemaLocale = "en-US"
schemaLogo = "me.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "hyas.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/rambleraptor"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/rambleraptor"

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "320"

### Image template
defaultImage = "me.png" # put in `./assets/images/`
fillImage = "1280x720 Center" # normalize image size
